/* eslint-disable */

// #Node Class
class Node {
  constructor(letter = null) {
    this.letter = letter;
    this.children = {};
    this.isCompleteWord = false;
  }
}

// #Trie class
class Trie {
  constructor() {
    this.root = new Node();
    this.wordCount = 0;
    this.selectedWords = [];
  }

  insert(word) {
    let wordArr = word.toLowerCase().split('');
    let currentNode = this.root;

    wordArr.forEach((letter) => {
      if (!currentNode.children[letter]) {
        currentNode.children[letter] = new Node(letter);
      }
      currentNode = currentNode.children[letter];
    });

    this.wordCount++
    currentNode.isCompleteWord = true;
  }

  count() {
    return this.wordCount;
  }

  suggest(string) {
    let stringArr = string.toLowerCase().split(''); // normalize string to LC and split into array of letters
    let currentNode = this.root; // assign currentNode var to start at the root node

    stringArr.forEach( letter => { // loop over all the letters in the string
      currentNode = currentNode.children[letter] // set the currentNode to its child node in the key of the current letter
    }) // end with the current node as the node for the last letter in the string array
    let wordCompletions = this.findWords(currentNode) // pass currentNode into fn that will return an array of partial word matches

    // map over wordCompletions arr and add the original search term to the begining of each word completion
    let suggestions = wordCompletions.map( solution => string + solution )

    this.selectedWords.forEach((word) => {  // loop over the selectedWords array
      if (suggestions.includes(word)) {  //  if any word is included in the suggestions
        let wordIndex = suggestions.indexOf(word); //  find what index its in
        let preferedWord = suggestions.splice(wordIndex, 1);  //  remove it from the array

        suggestions.unshift(...preferedWord)  //  add it back to the beggining of the array
      }
    })

    if (suggestions.length === 0) {
      return 'Not Found'
    }

    return suggestions
  }


  findWords(node, prefix = [], wordCompletions = []) {
    if (node === undefined) {
      return []
    }

    if (node.isCompleteWord) { //  if this node is the last node in a word
      wordCompletions.push(prefix.join(''))  //  join the letter(s) in the prefix array and push them into the completions array
    }
    let nodeChildrenKeys = Object.keys(node.children);  //  get the key names of this node's children object

    nodeChildrenKeys.forEach((letter) => {
      //  for each letter node's letter, push it into the prefix array
      prefix.push(node.children[letter].letter);
      // recursively call findWords on all children nodes of the current node until it returns a string to the wordCompletions array
      this.findWords(node.children[letter], prefix, wordCompletions);
      //  remove the iterated letter from the prefix array to make room for the next one in the forEach loop.
      prefix.pop();  //  ??
    })

    return wordCompletions
  }

  populate(array) {
    array.forEach((word) => {
      this.insert(word)
    });
  }

  select(string) {
    this.selectedWords.push(string)
  }

}

const villains = [
	"Abattoir",
	"Able Crown",
	"Abra Kadabra",
	"Absorbing Man",
	"Acolytes",
	"Acrobat",
	"Advanced Idea Mechanics",
	"Agamemno",
	"Agent H of HYDRA",
	"Al-Tariq",
	"Alberto Falcone",
	"Alex Wilder",
	"Alkhema",
	"Allatou",
	"Amazing Grace",
	"Amazo",
	"Americop",
	"Amos Fortune",
	"Amygdala",
	"Anaconda",
	"Anarky",
	"Animora",
	"Annihilus",
	"Anomaly",
	"Answer",
	"Anthony Lupus",
	"Apocalypse",
	"Appa Ali Apsa",
	"Aqueduct",
	"Arcade",
	"Aries",
	"Arkon",
	"Armadillo",
	"Artemis Crock",
	"Artemiz",
	"Asbestos Man",
	"Assembly of Evil",
	"Atomic Skull",
	"Attuma",
	"Axis Amerika",
	"Ballox the Monstroid",
	"Bane",
	"Baron Blitzkrieg",
	"Baron Blood",
	"Baron Mordo",
	"Baron Zemo",
	"Barracuda",
	"Batroc the Leaper",
	"Battleaxe",
	"Batzarro",
	"Bernadeth",
	"Bizarro",
	"Black Adam",
	"Black Flash",
	"Black Hand",
	"Black Knight",
	"Black Manta",
	"Black Mask",
	"Black Spider",
	"Black Talon",
	"Black Widow",
	"Black Zero",
	"Blackfire",
	"Blackout",
	"Blackrock",
	"Blacksmith",
	"Blastaar",
	"Blaze",
	"Blockbuster",
	"Bloodsport",
	"Bloody Mary",
	"Blue Snowman",
	"Blue Streak",
  "Boba Fett",
	"Bolivar Trask",
	"Brainiac",
	"Brainwave",
	"Bronze Tiger",
	"Brutale",
	"Bug-Eyed Bandit",
	"Bullseye",
	"Byth",
	"Calculator",
	"Calendar Man",
	"Captain Boomerang",
	"Captain Cold",
	"Captain Nazi",
	"Captain Stingaree",
	"Carmine Falcone",
	"Carnage",
	"Catman",
	"Catwoman",
	"Cavalier",
	"Chameleon",
	"Cheetah",
	"Cheshire",
	"Chessure",
	"Chronos",
	"Chthon",
	"Cicada",
	"Circe",
	"Clayface",
	"Clock King",
	"Cluemaster",
	"Cobalt Blue",
	"Cobalt Man",
	"Cold War",
	"Commissioner Gillian B. Loeb",
	"Composite Superman",
	"Conduit",
	"Constrictor",
	"Copperhead",
	"Cornelius Stirk",
	"Count Nefaria",
	"Count Vertigo",
	"Crazy Quilt",
	"Crime Doctor",
	"Crimesmith",
	"Crimson Dynamo",
	"Crossbones",
	"Crossfire",
	"Cutthroat",
	"Cyborgirl",
	"Dansen Macabre",
	"Dark Angel",
	"Darkseid",
	"Darth Vader",
	"David Cain",
	"Deacon Blackfire",
	"Deadline",
	"Deadpool",
	"Deadshot",
	"Death Storm",
	"Deathbird",
	"Deathbolt",
	"Deathstroke",
	"Decay",
	"Deep Six",
	"Desaad",
	"Despero",
	"Destiny",
	"Destroyer",
	"Deuce",
	"Deuce, Charger",
	"Devastation",
	"Devilance",
	"Diablo",
	"Diamond Lil",
	"Doctor Achilles Milo",
	"Doctor Alchemy",
	"Doctor Bedlam",
	"Doctor Cyber",
	"Doctor Demonicus",
	"Doctor Destiny",
	"Doctor Doom",
	"Doctor Double X",
	"Doctor Moon",
	"Doctor Octopus",
	"Doctor Phosphorus",
	"Doctor Poison",
	"Doctor Polaris",
	"Doctor Sivana",
	"Doctor Spectrum",
	"Dominus",
	"Doomsday",
	"Dormammu",
	"Double Dare",
	"Double Down",
	"Dr. Death",
	"Dr. Evil",
	"Dr. Horrible",
	"Dr. Light",
	"Dragon Man",
	"Dragonfly",
	"Dragonrider",
	"Duela Dent",
	"Eclipso",
	"Eduardo",
	"Effron the Sorcerer",
	"Egghead",
	"Electro",
	"Electrocutioner",
	"Elektro",
	"Emerald Empress",
	"Emma Frost",
	"Enchantress",
	"Equus",
	"Ereshkigal",
	"Evil Ernie",
	"Eviless",
	"Evinlea",
	"Executioner",
	"Exemplars",
	"Fabian Cortez",
	"Facade",
	"Factor Three",
	"Fadeaway Man",
	"Famine",
	"Faora",
	"Fatality",
	"Fault Zone",
	"Fearsome Five",
	"Fel Andar",
	"Felix Faust",
	"Fem Paragon",
	"Female Furies",
	"Fer-de-Lance",
	"Film Freak",
	"Fin Fang Foom",
	"Firebug",
	"Firefly",
	"Fisherman",
	"Fixer",
	"Flag-Smasher",
	"Floronic Man",
	"Freedom Force",
	"Frightful Four",
	"Galactus",
	"Gambler",
	"Gargantua",
	"Gargantus",
	"Gargoyle",
	"Gearhead",
	"Gemini",
	"General",
	"General Zod",
	"Gentleman Ghost",
	"Ghaur",
	"Giganta",
	"Gilotina",
	"Girder",
	"Gizmo",
	"Gladiator",
	"Glorious Godfrey",
	"Glorith",
	"Goddess",
	"Godiva",
	"Gog",
	"Golden Glider",
	"Goldface",
	"Goldilocks",
	"Googam",
	"Goom",
	"Gorilla Grodd",
	"Gorilla-Man",
	"Grand Director",
	"Granny Goodness",
	"Graviton",
	"Grayven",
	"Great White",
	"Green Goblin",
	"Griffin",
	"Grim Reaper",
	"Grottu",
	"Growing Man",
	"H.I.V.E.",
	"HYDRA",
	"Hades",
	"Halflife",
	"Hangman",
	"Hank Henshaw",
	"Harlequin",
	"Harley Quinn",
	"Harpy",
	"Hate-Monger",
	"Hath-Set",
	"Hazard",
	"Headlok",
	"Heat Wave",
	"Hector Hammond",
	"Heggra",
	"Hellgrammite",
	"High Evolutionary",
	"Hitman",
	"Hobgoblin",
	"Holiday",
	"Hugo Strange",
	"Hulk Robot",
	"Humpty Dumpty",
	"Hush",
	"Hyathis",
	"Hyena",
	"Hyperion",
	"Hypnota",
	"Ibac",
	"Ignition",
	"Immortus",
	"Impala",
	"Imperiex",
	"Impossible Man",
	"Indigo",
	"Inertia",
	"Infant Terrible",
	"Inferno",
	"Ingra",
	"Intergang",
	"Ion",
	"Iron Maiden",
	"Jack Frost",
	"Jack O'Lantern",
	"Jason Kreis",
	"Jason Todd",
	"Javelin",
	"Jax-Ur",
	"Jewelee",
	"Jigsaw",
	"Jinx",
	"Joker",
	"Juggernaut",
	"KGBeast",
	"Kalibak",
	"Kang the Conqueror",
	"Kanjar Ro",
	"Kanto",
	"Killer Croc",
	"Killer Frost",
	"Killer Moth",
	"King Ghidorah",
	"King Shark",
	"King Snake",
	"Kingpin",
	"Kira",
	"Kite Man",
	"Klaw",
	"Kleinstocks",
	"Knockout",
	"Korvac",
	"Kraven the Hunter",
	"Krona",
	"Kryptonite Man",
	"Kulan Gath",
	"Kurrgo",
	"Kyle Abbot",
	"Lady Clay",
	"Lady Death",
	"Lady Deathstrike",
	"Lady Dorma",
	"Lady Mastermind",
	"Lady Octopus",
	"Lady Shiva",
	"Lady Spellbinder",
	"Lady Vic",
	"Lagomorph",
	"Lashina",
	"Lava Men",
	"Law",
	"Lazara",
	"League of Assassins",
	"Leap-Frog",
	"Leather",
	"Legion of the Unliving",
	"Letha",
	"Lethal Legion",
	"Lex Luthor",
	"Lion-Mane",
	"Livewire",
	"Living Laser",
	"Lloigoroth",
	"Llyra",
	"Lock-Up",
	"Lodestone",
	"Loki",
	"Lorelei",
	"Lotso",
	"Lucifer",
	"Lynx",
	"MODOK",
	"Mace Blitzkrieg",
	"Mad Harriet",
	"Mad Hatter",
	"Mad Thinker",
	"Madame Masque",
	"Madame Rouge",
	"Madelyne Pryor",
	"Maelstrom",
	"Magenta",
	"Magneta",
	"Magneto",
	"Magpie",
	"Magus",
	"Mai Shen",
	"Major Disaster",
	"Major Force",
	"Malebolgia",
	"Malice",
	"Malice Vundabar",
	"Mammon",
	"Mammoth",
	"Man Beast",
	"Man-Bat",
	"Man-Killer",
	"Manchester Black",
	"Mandarin",
	"Mandarin's Minions",
	"Manhunters",
	"Mantis",
	"Marrow",
	"Massacre",
	"Master Mold",
	"Master Pandemonium",
	"Master of the World",
	"Mastermind",
	"Masters of Evil",
	"Matter Master",
	"Maxie Zeus",
	"Maxima",
	"Maximus",
	"Medusa",
	"Menace",
	"Mephisto",
	"Mercy",
	"Merlyn",
	"Metallo",
	"Midnight Sun",
	"Mimic",
	"Mindblast",
	"Miracle Man",
	"Mirror Master",
	"Misfit",
	"Mist",
	"Mister Hyde",
	"Mister Sinister",
	"Mole Man",
	"Molecule Man",
	"Molloch",
	"Moloid subterraneans",
	"Molten Man",
	"Molten Man-Thing",
	"Mongal",
	"Mongul",
	"Mongul II",
	"Monocle",
	"Monsieur Stigmonus",
	"Moondark",
	"Moonstone",
	"Morgan Edge",
	"Morgan le Fay",
	"Morlun",
	"Mortalla",
	"Mortician",
	"Moses Magnum",
	"Mothergod",
	"Mr. Felonious Gru",
	"Mr. Freeze",
	"Mr. Mxyzptlk",
	"Mr. Twister",
	"Mud Pack",
	"Murmur",
	"Mysteria",
	"Mysterio",
	"Mystique",
	"NKVDemon",
	"Naga",
	"Nebula",
	"Needle",
	"Nemesis Kid",
	"Nero",
	"Neron",
	"Neutron",
	"New Wave",
	"Nightmare",
	"Nocturna",
	"Northwind",
	"Nyssa Raatko",
	"O.G.R.E.",
	"Ocean Master",
	"Omega Red",
	"Onimar Synn",
	"Onomatopoeia",
	"Onslaught",
	"Orca",
	"Ord",
	"Orka",
	"Osira",
	"Overlord",
	"Owen Mercer",
	"Owlman",
	"Ozymandias",
	"Parademon",
	"Parademons",
	"Paragon",
	"Parallax",
	"Parasite",
	"Paste-Pot Pete",
	"Peek-a-Boo",
	"Penguin",
	"Penny Plunderer",
	"Persuader",
	"Phantazia",
	"Pharaoh Rama Tut",
	"Pharzoof",
	"Phobia",
	"Pied Piper",
	"Pink Pearl",
	"Plantman",
	"Plastique",
	"Poison Ivy",
	"Porcupine",
	"Portal",
	"Poundcakes",
	"Power Man",
	"Prank",
	"Prankster",
	"Pretty Persuasions",
	"Preus",
	"Princess Python",
	"Professor Hugo Strange",
	"Professor Ivo",
	"Professor Padraic Ratigan",
	"Prometheus",
	"Psycho-Man",
	"Psycho-Pirate",
	"Punisher",
	"Purgatori",
	"Quantum",
	"Queen Bee",
	"Queen Clea",
	"Queen of Fables",
	"Quicksand",
	"Quicksilver",
	"Qwsp",
	"Ra's al Ghul",
	"Rad",
	"Radioactive Man",
	"Rag Doll",
	"Rainbow Raider",
	"Rainbow Raiders",
	"Rampage",
	"Ratcatcher",
	"Reaper",
	"Red Ghost",
	"Red Hood",
	"Red Skull",
	"Resistants",
	"Reverse Flash",
	"Riddler",
	"Riddler's Daughter",
	"Ringmaster",
	"Ronan the Accuser",
	"Rose, Thorn",
	"Roulette",
	"Roxy Rocket",
	"Royal Flush Gang",
	"Rupert Thorne",
	"Russian",
	"SKULL",
	"Sabbac",
	"Sabretooth",
	"Salome",
	"Sandman",
	"Sat-Yr9",
	"Saturn Queen",
	"Savitar",
	"Scandal",
	"Scarecrow",
	"Scarlet Witch",
	"Scavenger",
	"Scorch",
	"Scorpia",
	"Scream",
	"Sebastian Shaw",
	"Selene",
	"Sensei",
	"Sentinels",
	"Set",
	"Shadow Thief",
	"Shark",
	"Shimmer",
	"Shredder",
	"Shriek",
	"Shrike",
	"Signalman",
	"Silk Fever",
	"Silver Banshee",
	"Silver Sable",
	"Silver Swan",
	"Sin",
	"Sinestro",
	"Sinister Six",
	"Snapdragon",
	"Solaris",
	"Solomon Grundy",
	"Sonar",
	"Southpaw",
	"Space Phantom",
	"Speed Queen",
	"Spellbinder",
	"Spencer Smythe",
	"Sphinx",
	"Spider Girl",
	"Spider-Woman",
	"Spiral",
	"Sportsmaster",
	"Spragg",
	"Stained Glass Scarlet",
	"Star Sapphire",
	"Starro",
	"Stegron",
	"Stompa",
	"Sun Girl",
	"Super-Skrull",
	"Superia",
	"Superman Revenge Squad",
	"Supreme Intelligence",
	"Swordsman",
	"Syndrome",
	"T.O. Morrow",
	"Tala",
	"Talia al Ghul",
	"Tally Man",
	"Talon",
	"Tar Pit",
	"Tarantula",
	"Tattooed Man",
	"Ten-Eyed Man",
	"Terra",
	"Terra-Man",
	"Terraxia",
	"Terrible Trio",
	"Thanos",
	"The Awesome Android",
	"The Basilisk",
	"The Blob",
	"The Borg",
	"The Chameleon",
	"The Crimson Ghost",
	"The Fat Man",
	"The Fiddler",
	"The Gargoyle",
	"The General",
	"The Joker",
	"The Kree",
	"The Leader",
	"The Lightning",
	"The Lizard",
	"The Mad Mod",
	"The Man-Killer",
	"The Mekon",
	"The Monk",
	"The Orb",
	"The Penguin",
	"The Puppet Master",
	"The Puzzler",
	"The Rhino",
	"The Rival",
	"The Scorpion",
	"The Separated Man",
	"The Shade",
	"The Shocker",
	"The Skrulls",
	"The Stranger",
	"The Terrible Tinkerer",
	"The Terrible Trio",
	"The Top",
	"The Vulture",
	"The Wingless Wizard",
	"The Wink",
	"The Yellow Claw",
	"They Who Wield Power",
	"Thinker",
	"Tigress",
	"Tim Boo Ba",
	"Titan",
	"Titania",
	"Titanium Man",
	"Titano",
	"Toad",
	"Tony Zucco",
	"Toyman",
	"Trickster",
	"Trigger Twins",
	"Trinity",
	"Tsunami",
	"Turtle",
	"Tweedledum",
	"Two-Face",
	"Typhoid Mary",
	"Ultra-Humanite",
	"Ultraman",
	"Ultron",
	"Umar",
	"Unicron",
	"Unus the Untouchable",
	"Ursa",
	"Valentina",
	"Vandal Savage",
	"Vanisher",
	"Vapor",
	"Venom",
	"Ventriloquist",
	"Vermin",
	"Vertigo",
	"Victor Zsasz",
	"Violator",
	"Viper",
	"Virman Vundabar",
	"Volcana",
	"Vulture",
	"Warlord Zemu",
	"Warmaker",
	"Weather Wizard",
	"Whiplash",
	"White Rabbit",
	"Winter Soldier",
	"Xemnu",
	"Yancy Street Gang",
	"Yellowjacket",
	"Yuga Khan",
	"Zaladane",
	"Zaran",
	"Zeiss",
	"Zoom",
	"Zsasz"
]

let trie = new Trie()
trie.populate(villains)

$('.search').on('input', function () {
  let searchTerm = $('.search').val()
  let suggestions = trie.suggest(searchTerm)

  $('.results').empty();

  if (suggestions === 'Not Found') {
    console.error('No Results Found');
    $('.results').append(`<div class="error">No Results Found</div>`)
    return
  }

  suggestions.forEach(word => {
    $('.results').append(`<li><button>${word}</button></li>`)
  })

  if (searchTerm.length === 0) {
    $('.results').empty();
  }
})


$('.insert-button').on('click', function() {
  let newVillian = $('.insert').val();
  trie.insert(newVillian)
  $('.insert').val('')
})


$('.results').on('click', 'button' , function() {
  console.log($(this));
  let value = $(this)[0].textContent
  trie.select(value)
})
